/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-06-06 09:56:06 
*/
import { IActor } from "modloader64_api/OOT/IActor";
import { IPuppet } from "./IPuppet";

export interface IHorseData {
    pointer: number;
    parent: IPuppet;
    puppet: IActor;
    pos: Buffer;
    rot: Buffer;
    anim_id: number;
    speed: number;
    toJSON(): any;
}
