/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-06-06 09:55:12 
*/
import { IModLoaderAPI } from "modloader64_api/IModLoaderAPI";
import { SmartBuffer } from "smart-buffer";
import { Age } from "modloader64_api/OOT/OOTAPI";
import { IPuppet } from "./IPuppet";

export interface IPuppetData {
    parent: IPuppet;
    pointer: number;
    ModLoader: IModLoaderAPI;
    header: SmartBuffer;
    buf: SmartBuffer;
    ageLastFrame: Age;
    age: Age;
    localCache: any;
    remoteCache: any;
    tickRate: number;
    tickCount: number;
    bundle: Buffer;
    getEntry(key: string): Buffer;
    onTick(): void;
    toJSON(): any;
}
