export const flags = {
    "flags": [
        "Entered Snowhead",
        "Entered Goron Shrine",
        "Entered Mountain Village",
        "Entered Gorman Racetrack",
        "Entered Romani Ranch",
        "Entered Ikana Graveyard",
        "Entered Termina Field",
        "Unknown 0",
        "Entered Ikana Canyon",
        "Entered Waterfall Rapids",
        "Entered Zora Hall",
        "Entered Pirates Fortress",
        "Entered Great Bay Coast",
        "Entered Deku Palace",
        "Entered Woodfall",
        "Entered Southern Swamp",
        "Entered Snowhead Temple",
        "Entered Woodfall Temple",
        "Entered North Clock Town",
        "Entered West Clock Town",
        "Entered East Clock Town",
        "Entered Inverted Stone Tower",
        "Entered Stone Tower",
        "Entered Ancient Castle of Ikana",
        "Entered Link Trial",
        "Entered Zora Trial",
        "Entered Goron Trial",
        "Entered Deku Trial",
        "Entered The Moon",
        "Entered Inverted Stone Tower Temple",
        "Entered Stone Tower Temple",
        "Entered Pirates Fortress Exterior",
        "Unknown 1",
        "Unknown 2",
        "Unknown 3",
        "Unknown 4",
        "Unknown 5",
        "Unknown 6",
        "Entered Deku Kings Chamber",
        "Unknown 7",
        "Unknown 8",
        "Unknown 9",
        "Unknown 10",
        "Unknown 11",
        "Unknown 12",
        "Unknown 13",
        "Unknown 14",
        "Unknown 15",
        "Unknown 16",
        "Unknown 17",
        "Unknown 18",
        "Unknown 19",
        "Unknown 20",
        "Unknown 21",
        "Unknown 22",
        "Unknown 23",
        "Learned Oath to Order",
        "Unknown 24",
        "Unknown 25",
        "Unknown 26",
        "Unknown 27",
        "Unknown 28",
        "Unknown 29",
        "Unknown 30",
        "Retrieved Clock Town Stray Fairy",
        "Clock Tower Opened",
        "Obtained Doggy Racetrack Piece of Heart",
        "Unknown 31",
        "Unknown 32",
        "Unknown 33",
        "Spoke to Monkey Outside Deku Kings Chamber",
        "DISABLE Minigame Disable All But B Button",
        "Taught Sonata of Awakening",
        "Gaebora Guides the Way to Lens Cave",
        "Spoke to Gaebora at Goron Village",
        "Spoke to Stone Tower Fairies Once",
        "Spoke to Great Bay Fairies Once",
        "Spoke to Snowhead Fairies Once",
        "Spoke to Woodfall Fairies Once",
        "Spoke to Clock Town Fairies Once",
        "Unknown 34",
        "Unknown 35",
        "Unknown 36",
        "Unknown 37",
        "Obtained Adult Wallet",
        "Unknown 38",
        "Unknown 39",
        "Kooloo Limpah Tingle Related",
        "Unknown 40",
        "Unknown 41",
        "Unknown 42",
        "Caught Bomber 5",
        "Caught Bomber 4",
        "Caught Bomber 3",
        "Caught Bomber 2",
        "Caught Bomber 1",
        "Obtained Magic Jar",
        "Deku Palace Guards Allow Passage",
        "Clock Town Guards Allow Passage",
        "Obtained Red Potion Bottle",
        "Gave Red Potion to Koume",
        "Saw at Skull Kid in Telescope",
        "Racing",
        "Water Purified in Woodfall Temple",
        "Completed Oceanside Spider House",
        "Obtained Giants Wallet",
        "Spoke to Oceanside Spider House Guy Once",
        "Unknown 43",
        "Spoke to Cremia in Barn Once",
        "Spoke to Cremia Once",
        "Unknown 44",
        "Killed All Eels",
        "Obtained Deku Flower Minigame Piece of Heart",
        "Deku Flower Minigame Beat Day 3",
        "Deku Flower Minigame Beat Day 2",
        "Deku Flower Minigame Beat Day 1",
        "Chateau Romani Infinite Magic",
        "Water Raised in Ikana Canyon",
        "Activated Sharp",
        "Protected Cremia   Obtained Romanis Mask",
        "Saw Kotake Leave to Look for Koume",
        "Unknown 45",
        "Unknown 46",
        "Spoke to Blue Gorman Bro Once",
        "Spoke to Orange Gorman Bro Once",
        "Unknown 47",
        "Unknown 48",
        "Unknown 49",
        "Unknown 50",
        "Spoke to Beaver Little Brother",
        "Unknown 51",
        "Spoke to Koume in Woods",
        "Took Off Transformation Mask 1",
        "Unknown 52",
        "Took Off Transformation Mask 0",
        "Unknown 53",
        "Obtained Land Title Deed",
        "Unknown 54",
        "Spoke to Clock Town Deku Merchant in First Cycle",
        "Spoke to Shikashi",
        "Unknown 55",
        "Deku Palace Caught in Gardens",
        "Unknown 56",
        "Unknown 57",
        "Received Powder Keg for Personal Use",
        "Received Powder Keg for Racetrack",
        "Spoke to Biggoron as Non Goron Once",
        "Unknown 58",
        "Unknown 59",
        "Unknown 60",
        "Unknown 61",
        "Spoke to Deku King Once",
        "Played Song of Healing for Darmani",
        "Zora Eggs Hatched",
        "Spoke to Lake Scientist as Zora Once",
        "Spoke to Lake Scientist as Deku Once",
        "Spoke to Lake Scientist as Goron Once",
        "Spoke to Lake Scientist Once",
        "Powder Keg 1",
        "Powder Keg 0",
        "Spoke to Mountain Smithy Once",
        "Learning New Wave Bossa Nova",
        "Raised Water in Darmanis Grave",
        "Darmani Waiting at Grave",
        "Darmani Waiting at Mountain Village",
        "Darmani Waiting at Two Islands",
        "Woodfall Temple Prison Entrance Raised   Water Cleansed",
        "Woodfall Temple Raised",
        "Unknown 62",
        "Spoke to Romani Once",
        "Practiced for Aliens with Romani",
        "Unknown 63",
        "Gorons Outside Grave Conversed",
        "Goron Outside Grave Spoke to Goron Link",
        "Unknown 64",
        "Mountain Smithy Hearth Melted",
        "Obtained Honey  Darling Piece of Heart",
        "Honey  Darling Beat Day 3",
        "Honey  Darling Beat Day 2",
        "Honey  Darling Beat Day 1",
        "Spoke to Goron Elders Son Once",
        "Played Lullaby for Goron Elders Son",
        "Obtained Milk Bottle",
        "Warded Off Aliens",
        "Obtained Beaver Bottle",
        "Unknown 65",
        "Deku Princess Returned to Palace1",
        "Unknown 66",
        "Spoke to Swamp Tourist Guide Once",
        "Dismissed Captain Keeta",
        "Woodfall Great Fairy Spin Attack",
        "Spoke to Goron in Goron Shrine Top As Goron Once",
        "Spoke to Goron in Goron Shrine Next to Baby Right Once",
        "Goron Elder Taught Lullaby Intro",
        "Unknown 67",
        "Spoke to Goron Elder Twice",
        "Unknown 68",
        "Won Against Little Brother Beaver",
        "Unknown 69", //nice
        "Won Against Big Brother Beaver",
        "Spoke to Fisherman Once as Zora",
        "Spoke to Seahorse at Fishermans Once 0",
        "Boat Cruise Purified Swamp",
        "Boat Cruise",
        "Raised Cuccos",
        "Unknown 70",
        "Giants Called to Clock Tower",
        "Obtained Beaver Piece of Heart",
        "Unknown 71",
        "Obtained Swamp Cruise Piece of Heart",
        "Unknown 72",
        "Spoke to Koume for Boat Cruise After Swamp Purification Once",
        "Gave Picture of Pirate to Fisherman",
        "Unknown 73",
        "Spoke to Seahorse at Fishermans Once 1",
        "Spoke to Fisherman Once as Link",
        "Postman Checked Postbox 2 1003 AM",
        "Postman Checked Postbox 1 930 AM",
        "Postbox 5 Deposited Letter to Kafei",
        "Postbox 4 Deposited Letter to Kafei",
        "Postbox 3 Deposited Letter to Kafei",
        "Postbox 2 Deposited Letter to Kafei",
        "Postbox 1 Deposited Letter to Kafei",
        "Spoke to Deku Butler in Deku Kings Chamber Once",
        "Spoke to Left Pot Zora As Zora Once",
        "Spoke to Left Pot Zora As Non Zora Once",
        "Unknown 74",
        "Postman Scheduled to Deliver Letter to Kafei Day 3",
        "Postman Scheduled to Deliver Letter to Kafei Day 2",
        "Postman Checked Postbox 5 1125 AM",
        "Postman Checked Postbox 4 1052 AM",
        "Postman Checked Postbox 3 1035 AM",
        "Deku Princess Returned to Palace2",
        "Woodfall Temple Prison Cut Open",
        "Mikau Collapsed on Shore",
        "Broke Zora Pots Once",
        "Spoke to Right Pot Zora As Non Zora Once",
        "Spoke to Right Pot Zora As Zora Once",
        "Unknown 75",
        "Unknown 76",
        "Wore Fierce Deity Mask Once",
        "Wore Zora Mask Once",
        "Wore Goron Mask Once",
        "Wore Deku Mask Once",
        "Took Out Ocarina for Japas",
        "Spoke to Japas As Zora Once",
        "Spoke to Japas As Non Zora Once",
        "Biggoron Fell Asleep",
        "Rode With Cremia Resets After Ride",
        "Rode With Cremia",
        "Unknown 77",
        "Unknown 78",
        "Played for Japas Once",
        "Tatls Second Cycle Text",
        "Tatls Ocean Hint Text1",
        "Tatls Snowhead Hint Text 0",
        "Great Bay Temple Frog Returned",
        "Woodfall Temple Frog Returned",
        "Attempted to Obtain Room Key",
        "Spoke to Tijo As Zora Once",
        "Spoke to Tijo As Non Zora Once",
        "Obtained Town Archery Piece of Heart",
        "Obtained Swamp Archery Piece of Heart",
        "Obtained Seahorse Piece of Heart",
        "Mountain Village Unfrozen",
        "Bought Day 3 Lottery Ticket",
        "Bought Day 2 Lottery Ticket",
        "Bought Day 1 Lottery Ticket",
        "Saved Bomb Shop Lady 0",
        "Obtained All Night Mask",
        "Laundry Pool Frog Returned",
        "Southern Swamp Frog Returned",
        "Unknown 79",
        "Unknown 80",
        "Unknown 81",
        "Unknown 82",
        "Obtained Mask of Truth",
        "Unknown 83",
        "Unknown 84",
        "Spoke to Mountain Village Frog",
        "Obtained Frog Piece of Heart",
        "Saw Don Gero",
        "Map Stone Tower",
        "Map Great Bay",
        "Map Romani Ranch",
        "Map Snowhead",
        "Map Woodfall",
        "Map Clock Town",
        "Unknown 85",
        "Spoke to Goron in Goron Shrine Bottom Left As Goron Once",
        "Spoke to Goron in Goron Shrine Bottom Left As Non Goron Once",
        "Unknown 86",
        "Unknown 87",
        "Unknown 88",
        "Spoke to Goron in Goron Shrine Bottom Right As Goron Once",
        "Spoke to Goron in Goron Shrine Bottom Right As Non Goron Once",
        "Spoke to Zora Guarding Japas Room As Non Zora Once",
        "Spoke to Zora Guarding Tijos Room Once",
        "Spoke to Zora Guarding Tijos Room As Non Zora Once",
        "Rock Sirloin Dropped",
        "Fed Rock Sirloin to Don Gero",
        "Unknown 89",
        "Spoke to Goron in Goron Shrine Next to Baby Left Once",
        "Unknown 90",
        "Spoke to Zora Sitting at Water in Zora Hall As Non Zora Once",
        "Listened to Guru Guru",
        "Unknown 91",
        "Spoke to Guru Guru in Stock Pot Inn Once",
        "Caught Peeping Zora",
        "Spoke to Zora Guarding Evans Room As Zora Once",
        "Spoke to Zora Guarding Evans Room As Non Zora Once",
        "Spoke to Zora Guarding Japas Room As Zora Once",
        "Spoke to Sound Check Guy As Zora Once",
        "Spoke to Sound Check Guy As Non Zora Once",
        "Obtained Evans Piece of Heart",
        "Spoke to Evan As Non Zora Once",
        "Spoke to Evan As Zora Once",
        "Spoke to Zora Atop Zora Hall As Zora Once",
        "Spoke to Zora Atop Zora Hall As Non Zora Once",
        "Spoke to Zora Sitting at Water in Zora Hall As Zora Once",
        "Spoke to Elders Son Outside Goron Racetrack Once",
        "Opened Goron Racetrack",
        "Unknown 92",
        "Spoke to Zora Wandering Around in Zora Hall As Zora Once",
        "Spoke to Zora Wandering Around in Zora Hall As Non Zora Once",
        "Spoke to Zora on Stage Once After Turning on Lights As Zora",
        "Spoke to Zora on Stage Once Before Turning on Lights As Zora",
        "Spoke to Zora on Stage Once Before Turning on Lights As Non Zora",
        "Unknown 93",
        "Helped Shiro",
        "Unknown 94",
        "Played Song for Evan",
        "Obtained Gold Dust Bottle",
        "Entered Goron Race",
        "Spoke to Elders Son at Racetrack Once",
        "Unknown 95",
        "Doggy Racetrack 0",
        "Doggy Racetrack 1",
        "Doggy Racetrack 2",
        "Doggy Racetrack 3",
        "Doggy Racetrack 4",
        "Doggy Racetrack 5",
        "Doggy Racetrack 6",
        "Doggy Racetrack 7",
        "Doggy Racetrack 8",
        "Doggy Racetrack 9",
        "Doggy Racetrack 10",
        "Doggy Racetrack 11",
        "Doggy Racetrack 12",
        "Doggy Racetrack 13",
        "Doggy Racetrack 14",
        "Doggy Racetrack 15",
        "Doggy Racetrack 16",
        "Doggy Racetrack 17",
        "Doggy Racetrack 18",
        "Doggy Racetrack 19",
        "Doggy Racetrack 20",
        "Doggy Racetrack 21",
        "Doggy Racetrack 22",
        "Doggy Racetrack 23",
        "Doggy Racetrack 24",
        "Doggy Racetrack 25",
        "Doggy Racetrack 26",
        "Doggy Racetrack 27",
        "Doggy Racetrack 28",
        "Doggy Racetrack 29",
        "Doggy Racetrack 30",
        "Doggy Racetrack 31",
        "Doggy Racetrack 32",
        "Doggy Racetrack 33",
        "Doggy Racetrack 34",
        "Doggy Racetrack 35",
        "Doggy Racetrack 36",
        "Doggy Racetrack 37",
        "Doggy Racetrack 38",
        "Doggy Racetrack 39",
        "Doggy Racetrack 40",
        "Doggy Racetrack 41",
        "Doggy Racetrack 42",
        "Doggy Racetrack 43",
        "Doggy Racetrack 44",
        "Doggy Racetrack 45",
        "Doggy Racetrack 46",
        "Doggy Racetrack 47",
        "Doggy Racetrack 48",
        "Doggy Racetrack 49",
        "Doggy Racetrack 50",
        "Doggy Racetrack 51",
        "Doggy Racetrack 52",
        "Doggy Racetrack 53",
        "Doggy Racetrack 54",
        "Doggy Racetrack 55",
        "Unknown 96",
        "Unknown 97",
        "Unknown 98",
        "Unknown 99",
        "Unknown 100",
        "Unknown 101",
        "Unknown 102",
        "Unknown 103",
        "Spoke to Kafei After Delivering Letter",
        "Unknown 104",
        "Obtained Letter to Kafei2",
        "Obtained Letter to Kafei1",
        "Promised to Meet Anju",
        "Obtained Four Giants storyPiece of Heart",
        "Obtained Carnival of storyPiece of Heart",
        "Played Full Ballad of the Wind Fish",
        "Unknown 105",
        "Couples Mask CutFinished",
        "Saved Suns Mask",
        "Sakons Hideout Open",
        "Obtained Pendant of Memories",
        "Hit Kafeis Bell",
        "Letter to Kafei Related",
        "Gave Pendant of Memories to Anju",
        "Spoke to Dampe Beneath the Graveyard Once",
        "Town Scrub Is in Grotto",
        "Beat Stone Tower Temple",
        "Approached Evan",
        "Unknown 106",
        "Unknown 107",
        "Unknown 108",
        "Protected Cremia 0",
        "Unknown 109",
        "Rode Turtle Once",
        "Woke Turtle",
        "Obtained Blue Potion Free",
        "Gave Mushrooms to Kotake",
        "Unknown 110",
        "Obtained Grotto Scrub Piece of Heart",
        "Unknown 111",
        "Mystery Man Disappeared",
        "Obtained Ghost Hut Piece of Heart",
        "Began Ghost Hut Minigame",
        "Unknown 112",
        "Unknown 113",
        "Unknown 114",
        "Unknown 115",
        "Unknown 116",
        "Beat Great Bay Temple",
        "Unknown 117",
        "Spoke to Anju in Laundry Pool Once",
        "Unknown 118",
        "Unknown 119",
        "Unknown 120",
        "Link the Goron Claims His Reservation 430 PM",
        "Unknown 121",
        "Played Ballad of the Wind Fish as Goron",
        "Played Ballad of the Wind Fish as Zora",
        "Played Ballad of the Wind Fish as Deku",
        "Played Ballad of the Wind Fish as Link",
        "Gorman Bros Race In Progress",
        "Spoke to Gorman Bros  With Horse Once",
        "Obtained Marine Lab Piece of Heart",
        "Unknown 122",
        "Spoke to Zora Shop Owner As Zora Once",
        "Unknown 123",
        "Unknown 124",
        "Spoke to Zora Shop Owner As Non Zora Once",
        "Obtained Chateau Romani Bottle",
        "Delivered Letter to Mama Directly",
        "Unknown 125",
        "Started Race with Gorman Bros",
        "Sakons Hideout Opening",
        "Bomb Shop Lady Entered North Clock Town",
        "Unknown 126",
        "Unknown 127",
        "Spoke to Goron Shop Owner As Goron Once",
        "Spoke to Goron Shop Owner As Non Goron Once",
        "Spoke to Mr Barten Preparing Milk Bar Once",
        "Unknown 128",
        "Protected Cremia 1",
        "Two Hundred Rupees in Bank",
        "Obtained Largest Quiver",
        "Obtained Large Quiver",
        "Unknown 129",
        "Entered South Clock Town",
        "Unknown 130",
        "Pamela Outside House",
        "Spoke to Mutoh on Final Night Once",
        "Unknown 131",
        "Unknown 132",
        "Obtained Couples Mask Piece of Heart",
        "Listened to Mayor Dotour Once",
        "Unknown 133",
        "Unknown 134",
        "Unknown 135",
        "Obtained Mountain Title Deed",
        "Unknown 136",
        "Spoke to Deku Scrub Once",
        "Obtained Swamp Title Deed",
        "Spotted by Sakon On His Way to Hideout",
        "Spotted by Pamela Once",
        "Kicked Out by Pamela",
        "Obtained Don Geros Mask",
        "Unknown 137",
        "Spoke to Ikana Scrub Once",
        "Gave Ocean Title Deed to Ikana Scrub",
        "Unknown 138",
        "Spoke to Zora Scrub Once",
        "Obtained Ocean Title Deed",
        "Unknown 139",
        "Spoke to Goron Scrub Once",
        "Showed Couples Mask to Mayor",
        "Spoke to Gorman Bros Wearing Circus Leader Mask Once",
        "Unknown 140",
        "Unknown 141",
        "Unknown 142",
        "Unknown 143",
        "Unknown 144",
        "Minigame Related",
        "Unknown 145",
        "Unknown 146",
        "Unknown 147",
        "Tingle 1",
        "Tingle 0",
        "Unknown 148",
        "Unknown 149",
        "Unknown 150",
        "Unknown 151",
        "Unknown 152",
        "Unknown 153",
        "Unknown 154",
        "Spoke to Mamamu Yan Once",
        "Unknown 155",
        "Unknown 156",
        "Unknown 157",
        "Notebook Row Madame Aroma",
        "Notebook Row Mayor Dotour",
        "Notebook Row Cremia",
        "Notebook Row Romani",
        "Notebook Row Bomb Shop Lady",
        "Notebook Row Curiosity Shop",
        "Notebook Row Kafei",
        "Notebook Row Anju",
        "Notebook Row Grog",
        "Notebook Row Kamaro",
        "Notebook Row Anjus Mom",
        "Notebook Row Toilet",
        "Notebook Row Rosa Sisters",
        "Notebook Row Postman",
        "Notebook Row Gorman",
        "Notebook Row Toto",
        "Notebook Item Letter to Kafei",
        "Notebook Item Promised to Meet Kafei",
        "Notebook Item Promised Anju Meetup",
        "Notebook Item Room Key",
        "Notebook Row Bombers",
        "Notebook Row Guru Guru",
        "Notebook Row Shiro",
        "Notebook Row Gorman Brothers",
        "Notebook Item Protected Milk",
        "Notebook Item Milk Bottle",
        "Notebook Item Protected Cows",
        "Notebook Item Promised to Romani",
        "Notebook Item Suns Mask Kafei",
        "Notebook Item Delivered Pendant",
        "Notebook Item Pendant of Memories",
        "Notebook Item Sent Letter to Kafei",
        "Notebook Item Rosa Sisters Piece of Heart",
        "Notebook Item Mayor Dotour Piece of Heart",
        "Notebook Item Bombers Code",
        "Obtained Notebook",
        "Notebook Item Chateau Romani",
        "Notebook Item Letter to Mama",
        "Notebook Item Keaton Mask",
        "Notebook Item Romanis Mask",
        "Notebook Item Garos Mask",
        "Notebook Item Bunny Mask",
        "Notebook Item All Night Mask",
        "Notebook Item Kafeis Mask",
        "Notebook Item Postman Piece of Heart",
        "Notebook Item Four Giants Piece of Heart",
        "Notebook Item Carnival of Piece of Heart",
        "Notebook Item Toilets Piece of Heart",
        "Unknown 158",
        "Notebook Item Bremen Mask",
        "Notebook Item Stone Mask",
        "Notebook Item Kamaros Mask",
        "Notebook Item Blast Mask",
        "Notebook Item Couples Mask",
        "Notebook Item Postmans Hat",
        "Notebook Item Circus Leaders Mask",
        "Entered Bombers Code",
        "Unknown 159",
        "Completed Bombers Hide  Seek",
        "Began Bombers Hide  Seek on Day 1",
        "Unknown 160",
        "Clock Town Deku Merchant Landed",
        "Spoke to Bomb Shop Lady Once",
        "Unknown 161",
        "Moons Tear Fell2",
        "Obtained Moons Tear",
        "Moons Tear Fell1",
        "Shikashi Automatically Spoke to Link",
        "Unknown 162",
        "Unknown 163",
        "Unknown 164",
        "Unknown 165",
        "Danced for Rosa Sisters 0",
        "Completed Bombers Hide  Seek Twice",
        "Played Song of Healing for Pamelas Father",
        "Obtained Room Key",
        "Shikashi Automatically Spoke to Goron or Zora Link",
        "Unknown 166",
        "Spoke to Gorman in Milk Bar Once",
        "Overheard Mr Barten  Gorman Conversation Once",
        "Spoke to Ghost in Secret Shrine",
        "Caught All Bombers",
        "Unknown 167",
        "Caught Bomber 5 1",
        "Caught Bomber 4 1",
        "Caught Bomber 3 1",
        "Caught Bomber 2 1",
        "Caught Bomber 1 1",
        "Spoke to Goron Elder After Beating Goht Once",
        "Moons Tear Quest Related",
        "Unknown 168",
        "Unknown 169",
        "Made All Grotto Gossip Stones the Same Color",
        "Danced for Rosa Sisters 1",
        "Bombers",
        "Obtained Postman Minigame Piece of Heart",
        "Unknown 170",
        "Unknown 171",
        "Unknown 172",
        "Spoke to Zora Near Pirates Fortress As Non Zora Once",
        "Spoke to Zora Near Pirates Fortress As Zora Once",
        "Unknown 173",
        "Spoke to Zora Near Pinnacle Rock As Zora Once",
        "Unknown 174",
        "Obtained Keaton Quiz Piece of Heart",
        "Killed Sakon",
        "Unknown 175",
        "Tatl Spoke About Clock Tower Entrance",
        "Scarecrow Fled",
        "Spoke to Guru Guru As Deku Once",
        "Spoke to Monkeys Outside Lost Woods",
        "Spoke to Lulu After Beating Gyorg Once",
        "Unknown 176",
        "Unknown 177",
        "Spoke to Guy Outside Ikana Hill",
        "Obtained Keaton Mask",
        "Unknown 178",
        "Clock Town Tatl",
        "Unknown 179",
        "Unknown 180",
        "Fed Marine Lab Fish 2 Once",
        "Fed Marine Lab Fish 1 Three Times",
        "Fed Marine Lab Fish 1 Twice",
        "Fed Marine Lab Fish 1 Once",
        "Obtained Postbox Piece of Heart",
        "Unknown 181",
        "Saved Bomb Shop Lady 1",
        "Tatl Angered by Sakon",
        "Spoke to Postman on Final Night Once",
        "Unknown 182",
        "DISABLE Disable  Hide C Buttons2",
        "Obtained Fisherman Piece of Heart",
        "DISABLE Disable  Hide C Buttons1",
        "Played Song of Healing for Kamaro",
        "Fed Marine Lab Fish 2 Three Times",
        "Fed Marine Lab Fish 2 Twice",
        "Unknown 183",
        "Unknown 184",
        "Pirate Related",
        "Unknown 185",
        "Began Swordsmans Lesson",
        "Popped Jims Balloon",
        "Pirates Fled Hookshot Room",
        "Dancing With Scarecrow",
        "Jim Left East Clock Town",
        "Obtained Red Potion for Koume",
        "Obtained Fierce Deity Mask",
        "Reunited Seahorses",
        "Unknown 186",
        "Unknown 187",
        "Unknown 188",
        "Unknown 189",
        "Postman Showing Priority Mail to Madame Aroma",
        "Triggered Fight With Captain Keeta",
        "Killed All Eels   Seahorse Position",
        "Unknown 190",
        "Unknown 191",
        "Overheard Employees Room Conversation",
        "Bombers Hide  Seek in Progress",
        "Bomber Related",
        "Entered Any Temple With Appropriate Remains",
        "Overheard Gorman  Mayors Receptionist Conversation Once",
        "Listened to Aroma Toto Gorman Once",
        "Overheard Anju  Link the Goron Conversation Once",
        "Overheard Anju  Postman Conversation Once",
        "Spoke to Town Scrub Once as Deku",
        "Spoke to Bomber Guarding Passage",
        "Postman Delivering Priority Mail",
        "Unknown 192",
        "Tatls Mountain Hint Text",
        "Tatls Ocean Hint Text",
        "Tatls Snowhead Hint Text 1",
        "Tatls Swamp Hint Text",
        "Obtained Tingle Picture Piece of Heart",
        "Triggered Couples Mask Cutscene",
        "Unknown 193",
        "Unknown 194",
        "Goron Shrine Opened",
        "Tatl Tells Link to Hurry at Clock Tower",
        "Pushed Mikau to Shore",
        "Unknown 195",
        "Unknown 196",
        "Spoke to Postman Giving Letter to Kafei",
        "Spoke to Captured Monkey Once",
        "Kafei in Sakons Hideout",
        "Postman Preparing to Flee Town",
        "Isnt that your horse",
        "Unknown 197",
        "Postman Delivered Priority Mail",
        "Spoke to Goron Guarding Goron Shrine Once",
        "Unknown 198",
        "Unknown 199",
        "Helped Toilet",
        "Boat at Deku Palace",
        "B Button Only Hides Others",
        "Obtained Gossip Stone Piece of Heart",
        "Letter to Kafei Picked up by Postman",
        "Obtained Postmans Hat",
        "Kafei Leaves to See Anju",
        "Postman Fled Town",
        "Unknown 200",
        "Unknown 201",
        "Unknown 202",
        "Saw Darmani at Grave",
        "Sent Letter to Kafei Late",
        "Sent Letter to Kafei On Time",
        "Mikau Performed His Song",
        "Mikau Requested Help",
        "Triggered Each a Is Loaded",
        "Unknown 203",
        "Unknown 204",
        "Unknown 205",
        "Spoke to Madame Aroma as Deku Once",
        "Unknown 206",
        "Finished Gorman Bros Race",
        "Started Gorman Bros Race Once",
        "Unknown 207",
        "Unknown 208",
        "Unknown 209",
        "Unknown 210",
        "Woke Turtle Once",
        "Unknown 211",
        "Completed Deku Shrine",
        "Beavers On Shore After First Two Races",
        "Unknown 212",
        "Unknown 213",
        "Unknown 214",
        "Unknown 215",
        "Unknown 216",
        "Unknown 217",
        "Unknown 218",
        "Unknown 219",
        "Unknown 220",
        "Unknown 221",
        "Unknown 222",
        "Unknown 223",
        "Unknown 224",
        "Unknown 225",
        "Unknown 226",
        "Unknown 227",
        "Unknown 228",
        "Unknown 229",
        "Unknown 230",
        "Unknown 231",
        "Unknown 232",
        "Unknown 233",
        "Unknown 234",
        "Unknown 235",
        "Unknown 236",
        "Unknown 237",
        "Unknown 238",
        "Unknown 239",
        "Unknown 240",
        "Unknown 241",
        "Unknown 242",
        "Unknown 243",
        "Unknown 244",
        "Unknown 245",
        "Unknown 246",
        "Unknown 247",
        "Unknown 248",
        "Unknown 249",
        "Unknown 250",
        "Unknown 251",
        "Unknown 252",
        "Unknown 253",
        "Unknown 254",
        "Unknown 255",
        "Unknown 256",
        "Unknown 257",
        "Unknown 258",
        "Unknown 259"
    ]
}