#define WAIST 1
#define RTHIGH 3
#define RSHIN 4
#define RFOOT 5
#define LTHIGH 6
#define LSHIN 7
#define LFOOT 8
#define HEAD 10
#define HAT 11
#define COLLAR 12
#define LSHOULDER 13
#define LFOREARM 14
#define RSHOULDER 16
#define RFOREARM 17
#define TORSO 20
#define RHAND 18
#define LHAND 15
#define SHEATH 19