/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-03-02 22:34:46 
*/
import { IOOTCore } from "modloader64_api/OOT/OOTAPI";
import { IModLoaderAPI } from "modloader64_api/IModLoaderAPI";

export interface IPuppetData {
    pointer: number;
    ModLoader: IModLoaderAPI;
    core: IOOTCore;
    pos: Buffer;
    rot: Buffer;
    toJSON(): any;
}
